version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devflix
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql   # persistência dos dados do banco
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: flask_api
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app   # monta o código local no container (dev mais fácil)

volumes:
  mysql_data:   # volume nomeado para persistir os dados
